name: release
on:
  release:
    types: [ created ]

jobs:
  build-release:
    name: Build Release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*
          token: ${{ secrets.GITHUB_TOKEN }}
